# tf.errors.OutOfRangeError

View source on GitHub  Raised when an operation iterates past the valid input
range. Inherits From: `OpError`

#### View aliases

Compat aliases for migration See Migration guide for more details.
`tf.compat.v1.errors.OutOfRangeError`

    
    tf.errors.OutOfRangeError(
        node_def, op, message
    )
    
This exception is raised in "end-of-file" conditions, such as when a `tf.QueueBase.dequeue` operation is blocked on an empty queue, and a `tf.QueueBase.close` operation executes. | Attributes  
---  
`error_code` |  The integer error code that describes the error.   
`message` |  The error message that describes the error.   
`node_def` |  The `NodeDef` proto representing the op that failed.   
`op` |  The operation that failed, if known. 
> Note: If the failed op was synthesized at runtime, e.g. a `Send` or `Recv`
> op, there will be no corresponding `tf.Operation` object. In that case, this
> will return `None`, and you should instead use the
> `tf.errors.OpError.node_def` to discover information about the op.  
Â© 2020 The TensorFlow Authors. All rights reserved.  
Licensed under the Creative Commons Attribution License 3.0.  
Code samples licensed under the Apache 2.0 License.  
https://www.tensorflow.org/versions/r2.4/api_docs/python/tf/errors/OutOfRangeError

  *[ISP]: Internet Service Provider
  *[LIFO]: last-in, first-out
  *[FIFO]: first-in, first-out

