<h1>pandas.errors.UnsortedIndexError</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.UnsortedIndexError"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">UnsortedIndexError</span></span><a class="reference external" href="https://github.com/pandas-dev/pandas/blob/v1.4.0/pandas/errors/__init__.py#L46-L50"><span class="viewcode-link"><span class="pre">[source]</span></span></a>
</dt> <dd>
<p>Error raised when attempting to get a slice of a MultiIndex, and the index has not been lexsorted. Subclass of <cite>KeyError</cite>.</p> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/1.4.0/reference/api/pandas.errors.UnsortedIndexError.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/1.4.0/reference/api/pandas.errors.UnsortedIndexError.html</a>
  </p>
</div>
