<h1>sklearn.exceptions.UndefinedMetricWarning</h1> <dl class="py class"> <dt id="sklearn.exceptions.UndefinedMetricWarning">
<code>class sklearn.exceptions.UndefinedMetricWarning</code> <a class="reference external" href="https://github.com/scikit-learn/scikit-learn/blob/95119c13a/sklearn/exceptions.py#L138"><span class="viewcode-link">[source]</span></a>
</dt> <dd>
<p>Warning used when the metric is invalid</p> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 0.18: </span>Moved from sklearn.base.</p> </div> <dl class="field-list simple"> <dt class="field-odd">Attributes</dt> <dd class="field-odd">
<dl class="simple"> <dt><strong>args</strong></dt>
 </dl> </dd> </dl> <h4 class="rubric">Methods</h4> <table class="longtable docutils align-default">   <tr>
<td><p><a class="reference internal" href="#sklearn.exceptions.UndefinedMetricWarning.with_traceback" title="sklearn.exceptions.UndefinedMetricWarning.with_traceback"><code>with_traceback</code></a></p></td> <td><p>Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.</p></td> </tr>  </table> <dl class="py method"> <dt id="sklearn.exceptions.UndefinedMetricWarning.with_traceback">
<code>with_traceback()</code> </dt> <dd>
<p>Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.</p> </dd>
</dl> </dd>
</dl> <div class="_attribution">
  <p class="_attribution-p">
    &copy; 2007&ndash;2020 The scikit-learn developers<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://scikit-learn.org/0.24/modules/generated/sklearn.exceptions.UndefinedMetricWarning.html" class="_attribution-link">https://scikit-learn.org/0.24/modules/generated/sklearn.exceptions.UndefinedMetricWarning.html</a>
  </p>
</div>
