# sklearn.exceptions.DataDimensionalityWarning

`class sklearn.exceptions.DataDimensionalityWarning` [source]

    
Custom warning to notify potential issues with data dimensionality.

For example, in random projection, this warning is raised when the number of
components, which quantifies the dimensionality of the target projection
space, is higher than the number of features, which quantifies the
dimensionality of the original source space, to imply that the dimensionality
of the problem will not be reduced.

Changed in version 0.18: Moved from sklearn.utils.

Attributes

    
args

#### Methods

`with_traceback` | Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.  
---|---  
`with_traceback()`

    
Exception.with_traceback(tb) – set self.__traceback__ to tb and return self.

© 2007–2020 The scikit-learn developers  
Licensed under the 3-clause BSD License.  
https://scikit-
learn.org/0.24/modules/generated/sklearn.exceptions.DataDimensionalityWarning.html

